[general]
import = [
    "~/.config/alacritty/themes/themes/autumn.toml"
]

# Themes from https://github.com/alacritty/alacritty-theme

[window]
decorations = "None"
opacity = 0.85
blur = true

[window.padding]
x = 10
y = 10
